### PR TITLE
Fix issue where cascading network timeouts compound on each other

### PR DESCRIPTION
**Pull request by bsneed**
Fixes issue #152 

It was observed that when network traffic is blocked that outbound requests are timing out after 60 seconds, however the flush interval has a default of 30 seconds.  This would result in a cascading set of outbound network requests that would all fail.

This change makes it such that in the case where connectivity is unavailable, we pause the flush timer for 5 minutes before attempting again.

### CODE REVIEW

**Review by prayansh — APPROVED** [review]
LGTM 🚢

**Comment by brianmichel** [comment]
Hey folks, any ETA on when this will land? We're going to be adding a work around to our fork as well, but would love to pick up the main line solution when possible, thanks!

**Comment by eco-travis** [comment]
@prayansh Any idea on when this might get merged?  This PR seems to be getting pretty stale.

**Comment by bclous** [comment]
@bsneed, any reason why this hasn't been merged? This is causing major issues in our app. It seems anyone with an ad blocker is getting a CPU spike within 45 seconds and crashing.

**Comment by brianmichel** [comment]
> @bsneed, any reason why this hasn't been merged? This is causing major issues in our app. It seems anyone with an ad blocker is getting a CPU spike within 45 seconds and crashing.

Hey @bclous dunno if you need a quick solution, we ended up adding an API that allows you to only keep a maximum number of files on disk to ensure that we wouldn't accumulate too many files and cause all kinds of issues for certain folks. It's here if you want it https://github.com/thebrowsercompany/analytics-swift/pull/1 should be straightforward to cherry-pick into your own fork.

**Comment by bclous** [comment]
> > @bsneed, any reason why this hasn't been merged? This is causing major issues in our app. It seems anyone with an ad blocker is getting a CPU spike within 45 seconds and crashing.
> 
> Hey @bclous dunno if you need a quick solution, we ended up adding an API that allows you to only keep a maximum number of files on disk to ensure that we wouldn't accumulate too many files and cause all kinds of issues for certain folks. It's here if you want it [thebrowsercompany#1](https://github.com/thebrowsercompany/analytics-swift/pull/1) should be straightforward to cherry-pick into your own fork.

Thanks for the reply. Is this only in the browser company's fork? and Not in the current 1.3.2 version?

**Comment by bsneed** [comment]
@bclous @brianmichel the original reporter of the bug suggested it didn't go far enough.  The attached bug report has more of the conversation.  We have a solution, but haven't had the bandwidth to implement just yet.  The reporter of the issue had a fork with a temporary workaround that got him going again.  It may be worth it to check that out in the meantime.  If you have a Segment account, reaching out directly to support will help get this prioritized.

**Comment by bclous** [comment]
> @bclous @brianmichel the original reporter of the bug suggested it didn't go far enough. The attached bug report has more of the conversation. We have a solution, but haven't had the bandwidth to implement just yet. The reporter of the issue had a fork with a temporary workaround that got him going again. It may be worth it to check that out in the meantime. If you have a Segment account, reaching out directly to support will help get this prioritized.

Got it, thanks for all the info

**Comment by bsneed** [comment]
@bclous as a follow up; I just made the case in our sprint planning to get this done.  I've assigned an engineer to take a first stab at it on another platform and will bring that over once he's got the kinks worked out.  The idea is we'd implement a flush policy that developers could customize to gain more control over how flushing works.

The idea is that for your particular use case(s) you would be able to implement a policy that could do this like ...

example 1: network requests are failing, so back off on the flush interval.

example 2: event storage is piling up, so start culling files.

etc.

**Comment by bclous** [comment]
@bsneed thanks, I think that makes sense. We had an extremely similar problem in our custom infra at FB. Unsent events were piling up on disk and causing all sorts of performance issues. 

Would be great to have greater control over flushing and which events should absolutely be stored versus events that we're fine dropping if need be.

**Comment by brianmichel** [comment]
> > > @bsneed, any reason why this hasn't been merged? This is causing major issues in our app. It seems anyone with an ad blocker is getting a CPU spike within 45 seconds and crashing.
> > 
> > 
> > Hey @bclous dunno if you need a quick solution, we ended up adding an API that allows you to only keep a maximum number of files on disk to ensure that we wouldn't accumulate too many files and cause all kinds of issues for certain folks. It's here if you want it [thebrowsercompany#1](https://github.com/thebrowsercompany/analytics-swift/pull/1) should be straightforward to cherry-pick into your own fork.
> 
> Thanks for the reply. Is this only in the browser company's fork? and Not in the current 1.3.2 version?

Yup, this is our fork which is up to date with the 1.3.1 release from Segment. I can merge upstream if you needed something specific from 1.3.2, however we also specifically omit tracking information so I don't think you should take it wholesale without taking a peek through the changes that are unique to our fork, hence suggesting you fork and cherry-pick where needed.

**Comment by bsneed** [comment]
Fixed in 1.4.4 via Flush Policy and an example flush policy implementation here: https://github.com/segmentio/analytics-swift/blob/main/Examples/tasks/NetBlockerFlushPolicy.swift

**Pull request closed without merging**
